field: 46458d94-5e9b-449e-b35f-86dbe936e8ea # Page Content
fieldLayouts:
  0dafa6c3-a15f-495c-a259-ecca441f3819:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bc9368b5-daf7-4a80-bb1a-a0abf1bf05fd # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c16658fc-72a8-4fa7-a458-a07cc57871de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 91401bc9-eb46-486e-9070-acbb71d337aa # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d942ac5b-0d9b-4f98-b6b5-c6d5e8d57944
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc87658f-35c4-4f89-9150-a5aada535b4b # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd2738a6-af87-4d7a-b5fd-596c29a708ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7431f890-8342-455f-b058-b911e1222411
        userCondition: null
fields:
  91401bc9-eb46-486e-9070-acbb71d337aa: # Details
    columnSuffix: aqhnpfpn
    contentColumnType: text
    fieldGroup: null
    handle: details
    instructions: null
    name: Details
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bc9368b5-daf7-4a80-bb1a-a0abf1bf05fd: # Heading
    columnSuffix: wsdopodk
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dc87658f-35c4-4f89-9150-a5aada535b4b: # Background Color
    columnSuffix: sqmyboxx
    contentColumnType: string(5)
    fieldGroup: null
    handle: backgroundColor
    instructions: 'This color will cover the full background of the block.'
    name: 'Background Color'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: copy
name: Copy
sortOrder: 1
