field: 46458d94-5e9b-449e-b35f-86dbe936e8ea # Page Content
fieldLayouts:
  9778f5e8-9852-4d1b-bc3e-c0d3909c242a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c555c62-b18e-4cac-99be-00e3eae00db9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 301c3531-86ef-477d-89c4-0418e60c125a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c39e8c9d-53b0-4ece-a264-7e85f6fea101 # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aabeb5cb-4875-4df3-a71e-90ec28a9baa6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c34313e-c444-4f80-aa04-af383705367f # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92ff3aa3-0add-4771-8a6f-4b7e1e5289fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 971e5769-90d2-40cf-a922-a6dc168fabab # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebd1f749-2ee1-4318-9c35-3fd80373a1c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e3fef528-f54b-4a63-8996-034576785af4
        userCondition: null
fields:
  8c555c62-b18e-4cac-99be-00e3eae00db9: # Heading
    columnSuffix: oqirlizb
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c34313e-c444-4f80-aa04-af383705367f: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9e084d53-a57f-431a-b80f-fb551ccf2bca' # images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9e084d53-a57f-431a-b80f-fb551ccf2bca' # images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  971e5769-90d2-40cf-a922-a6dc168fabab: # Background Color
    columnSuffix: twohglye
    contentColumnType: string(5)
    fieldGroup: null
    handle: backgroundColor
    instructions: 'This color will cover the full background of the block.'
    name: 'Background Color'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c39e8c9d-53b0-4ece-a264-7e85f6fea101: # Details
    columnSuffix: fgmfhnch
    contentColumnType: text
    fieldGroup: null
    handle: details
    instructions: null
    name: Details
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: gallery
name: Gallery
sortOrder: 2
