columnSuffix: ctviefbn
contentColumnType: text
fieldGroup: b59f69d9-bcca-4d1d-8a54-4a840e3ee97c # Common
handle: ctaLink
instructions: null
name: 'CTA Link'
searchable: false
settings:
  allowCustomText: false
  allowTarget: false
  defaultText: null
  selectLinkText: ''
  types:
    __assoc__:
      -
        - presseddigital\linkit\models\Url
        -
          __assoc__:
            -
              - enabled
              - 1
      -
        - presseddigital\linkit\models\Entry
        -
          __assoc__:
            -
              - enabled
              - 1
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
